apiVersion: v1
kind: Service
metadata:
  name: anubis-docs
spec:
  selector:
    app: anubis-docs
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 8081
    targetPort: 8081
    name: anubis
