name: Sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push tarball
        run: |
          find . ! -name .github/workflows/sync.yml -exec rm -rf {} +
          TAG_NAME=gh release list -R TecharoHQ/anubis --json tagName,isLatest -q '(.[] | select(.isLatest)).tagName'
          gh release download -R TecharoHQ/anubis -O - -p 'anubis-src-vendor-npm-*.tar.gz' "$TAG_NAME" | tar xzvf --exclude='.github/*' -
          npm install
          npm run build
          git commit -am "$TAG_NAME"
          git tag "$TAG_NAME"
          git push --tags
