name: Sync

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Push tarball
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.github' -exec rm -rf {} +
          TAG_NAME=$(gh release list -R TecharoHQ/anubis --json tagName,isLatest -q '(.[] | select(.isLatest)).tagName')
          if [[ $(git ls-remote -qt origin "$TAG_NAME") ]]; then exit; fi
          gh release download -R TecharoHQ/anubis -O - -p 'anubis-src-vendor-npm-*.tar.gz' "$TAG_NAME" | tar xzf - --exclude='.github/*' --exclude='.gitignore' --strip-components 1
          git add -A
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "$TAG_NAME"
          git tag "$TAG_NAME"
          git push && git push --tags
